### PR TITLE
Ported Akka.Quartz.Actor to .Net Standard 2.0. Updated Akka.net to v1.4.0-beta1, Quartz to v3.0.7.

### PR DESCRIPTION
**Pull request by mrjin-syd**
And fixed Unit test case accordingly.

### CODE REVIEW

**Comment by Danthar** [comment]
@mrjin-syd looks ok. Ill need to verify locally.

**Comment by Danthar** [comment]
@Aaronontheweb since CI is gone here, whats our story on getting this published (if we merge this), considering secret nuget keys and such ?

**Comment by Aaronontheweb** [comment]
@Danthar I can get CI set back up - we need to copy the YAML files and build.fsx from here: https://github.com/akkadotnet/Akka.Streams.Kafka

they're all standardized so no configuration changes other than some of the Github values are needed

**Comment by Danthar** [comment]
Merging this, in order to bring the CI up to date i practically need to do the same stuff. No sense i doing this work double

**Comment by Danthar** [comment]
although i probably downgrade to the latest akka-stable

**Pull request merged**
