### PR TITLE
update version to 1.3.1

### PR DESCRIPTION
**Pull request by maxim-s**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
thanks @maxim-s !

**Comment by Aaronontheweb** [comment]
@maxim-s although, the actual NuGet dependencies for this package haven't been updated yet - could you please add those?

**Comment by maxim-s** [comment]
@Aaronontheweb what kind of dependencies do you mean?

**Comment by object** [comment]
@Aaronontheweb If you mean dependencies in packages.config they were updated to 1.3.1 in the previous PR.

**Comment by Danthar** [comment]
Can confirm package references are ok. With the exception of:
`
    <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net452" />`

afaik we still target version 9 of newtonsoft

**Comment by maxim-s** [comment]
@Danthar ok, I'll change it in this PR, thank you

**Pull request merged**
